---
director_name: "Bosh Lite Director"
internal_ip: 192.168.50.6
internal_gw: 192.168.50.1
internal_cidr: 192.168.50.0/24
outbound_network_name: NatNetwork
network_type: nat
network_device: eno1

director_vm_cpus: 2
director_vm_ram_bytes: 8192
director_vm_ephemeral_disk_megabytes: 10240

director_vm_dns_recursors:
  - 8.8.4.4
  - 8.8.8.8
